/*
 * 橘瓣 OrangeChat
 * 衍生自 RikkaHub (https://github.com/rikkahub/rikkahub)，原作者 RE
 * 本项目基于 GNU AGPL v3 开源，详见根目录 LICENSE 文件
 */

package me.rerere.rikkahub.data.ai.tools

import android.app.WallpaperManager
import android.content.Context
import android.graphics.BitmapFactory
import java.io.File
import java.net.HttpURLConnection
import java.net.URL
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import kotlinx.serialization.json.add
import kotlinx.serialization.json.buildJsonObject
import kotlinx.serialization.json.contentOrNull
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import kotlinx.serialization.json.put
import kotlinx.serialization.json.putJsonArray
import kotlinx.serialization.json.putJsonObject
import kotlin.io.encoding.Base64
import kotlin.io.encoding.ExperimentalEncodingApi
import me.rerere.ai.core.InputSchema
import me.rerere.ai.core.MessageRole
import me.rerere.ai.core.Tool
import me.rerere.ai.ui.UIMessage
import me.rerere.ai.ui.UIMessagePart
import me.rerere.common.android.Logging
import me.rerere.rikkahub.data.files.FilesManager

@OptIn(ExperimentalEncodingApi::class)
fun createSetWallpaperTool(
    context: Context,
    recentMessages: List<UIMessage> = emptyList(),
    filesManager: FilesManager? = null,
): Tool = Tool(
    name = "set_wallpaper",
    needsApproval = true,
    description = "Set device wallpaper using the most recent image in the current conversation. " +
        "Automatically finds the latest image (sent by user or generated by assistant) from chat history - no file path needed. " +
        "Supports home screen, lock screen, or both.",
    parameters = {
        InputSchema.Obj(
            properties = buildJsonObject {
                putJsonObject("target") {
                    put("type", "string")
                    put("description", "Which wallpaper to set: home, lock, or both. Default: both")
                    putJsonArray("enum") { add("home"); add("lock"); add("both") }
                }
                putJsonObject("image_source") {
                    put("type", "string")
                    put("description", "Filter which image source to use: 'user' for images sent by user, 'assistant' for images generated/captured by assistant. If omitted, uses the most recent image regardless of source.")
                    putJsonArray("enum") { add("user"); add("assistant") }
                }
            }
        )
    },
    execute = { args ->
        val params = args.jsonObject
        val target = params["target"]?.jsonPrimitive?.contentOrNull ?: "both"
        val imageSource = params["image_source"]?.jsonPrimitive?.contentOrNull

        if (target !in listOf("home", "lock", "both")) {
            return@Tool listOf(UIMessagePart.Text(
                buildJsonObject { put("success", false); put("error", "target must be one of: home, lock, both") }.toString()
            ))
        }

        if (imageSource != null && imageSource !in listOf("user", "assistant")) {
            return@Tool listOf(UIMessagePart.Text(
                buildJsonObject { put("success", false); put("error", "image_source must be one of: user, assistant, or omitted") }.toString()
            ))
        }

        // Find the most recent image from conversation history (reverse order)
        val targetRole = when (imageSource) {
            "user" -> MessageRole.USER
            "assistant" -> MessageRole.ASSISTANT
            else -> null
        }

        val foundImage = recentMessages
            .reversed()
            .filter { message -> targetRole == null || message.role == targetRole }
            .flatMap { message -> message.parts.filterIsInstance<UIMessagePart.Image>() }
            .firstOrNull()

        if (foundImage == null) {
            val sourceDesc = when (imageSource) {
                "user" -> "sent by user"
                "assistant" -> "generated by assistant"
                else -> "from any source"
            }
            return@Tool listOf(UIMessagePart.Text(
                buildJsonObject {
                    put("success", false)
                    put("error", "no image found in this conversation matching the criteria (looking for image $sourceDesc)")
                }.toString()
            ))
        }

        try {
            val imageUrl = foundImage.url
            Logging.log("SetWallpaperTool", "Found image url: $imageUrl")

            // Resolve the image to a File based on its URL scheme
            val imageFile = withContext(Dispatchers.IO) {
                resolveImageToFile(context, imageUrl, filesManager)
            }

            if (imageFile == null) {
                return@Tool listOf(UIMessagePart.Text(
                    buildJsonObject {
                        put("success", false)
                        put("error", "Failed to resolve image. Unsupported URL scheme or download failed: $imageUrl")
                    }.toString()
                ))
            }

            if (!imageFile.exists() || !imageFile.isFile) {
                Logging.log("SetWallpaperTool", "File not found: ${imageFile.absolutePath}")
                return@Tool listOf(UIMessagePart.Text(
                    buildJsonObject { put("success", false); put("error", "File not found: ${imageFile.absolutePath}") }.toString()
                ))
            }

            val bitmap = withContext(Dispatchers.IO) {
                BitmapFactory.decodeFile(imageFile.absolutePath)
            }
            if (bitmap == null) {
                Logging.log("SetWallpaperTool", "Failed to decode image: ${imageFile.absolutePath}")
                return@Tool listOf(UIMessagePart.Text(
                    buildJsonObject { put("success", false); put("error", "Failed to decode image file") }.toString()
                ))
            }

            val wm = WallpaperManager.getInstance(context)
            if (wm == null) {
                Logging.log("SetWallpaperTool", "WallpaperManager unavailable")
                return@Tool listOf(UIMessagePart.Text(
                    buildJsonObject { put("success", false); put("error", "WallpaperManager unavailable") }.toString()
                ))
            }

            val flags = when (target) {
                "home" -> WallpaperManager.FLAG_SYSTEM
                "lock" -> WallpaperManager.FLAG_LOCK
                else -> WallpaperManager.FLAG_SYSTEM or WallpaperManager.FLAG_LOCK
            }

            wm.setBitmap(bitmap, null, true, flags)

            listOf(UIMessagePart.Text(
                buildJsonObject {
                    put("success", true)
                    put("target", target)
                    put("image_source", imageSource ?: "any")
                    put("message", "Wallpaper set for $target using the most recent image in conversation")
                }.toString()
            ))
        } catch (e: Exception) {
            Logging.log("SetWallpaperTool", "Error: ${e.message}\n${e.stackTraceToString()}")
            listOf(UIMessagePart.Text(
                buildJsonObject {
                    put("success", false)
                    put("error", e.message ?: "Failed to set wallpaper")
                }.toString()
            ))
        }
    }
)

/**
 * Resolve an image URL string to a local File.
 *
 * Supported schemes:
 * - file:// -> directly use the file
 * - data:image/...;base64,... -> decode base64 and write to a temp file (reuses createImageFileFromBase64 logic)
 * - http(s):// -> download to a temp file (reuses saveMessageImage download pattern)
 *
 * Returns null if the scheme is unsupported or download fails.
 */
@OptIn(ExperimentalEncodingApi::class)
private suspend fun resolveImageToFile(context: Context, imageUrl: String, filesManager: FilesManager? = null): File? = withContext(Dispatchers.IO) {
    when {
        // Local file path
        imageUrl.startsWith("file://") -> {
            val filePath = imageUrl.removePrefix("file://")
            File(filePath)
        }

        // Absolute path without scheme
        imageUrl.startsWith("/") -> {
            File(imageUrl)
        }

        // Base64 inline image - reuse FilesManager.createImageFileFromBase64 if available
        imageUrl.startsWith("data:image") -> {
            val tempDir = context.filesDir.resolve("images")
            if (!tempDir.exists()) tempDir.mkdirs()
            val tempFile = File(tempDir, "wallpaper_${System.currentTimeMillis()}.png")
            if (filesManager != null) {
                // Reuse FilesManager's createImageFileFromBase64 method
                filesManager.createImageFileFromBase64(imageUrl, tempFile.absolutePath)
            } else {
                // Fallback: decode base64 directly (same logic as createImageFileFromBase64)
                val base64Data = imageUrl.substringAfter("base64,")
                val byteArray = Base64.decode(base64Data.toByteArray())
                tempFile.writeBytes(byteArray)
                tempFile
            }
        }

        // Remote HTTP/HTTPS image - download to temp file
        imageUrl.startsWith("http://") || imageUrl.startsWith("https://") -> {
            runCatching {
                val url = URL(imageUrl)
                val connection = url.openConnection() as HttpURLConnection
                connection.connectTimeout = 15000
                connection.readTimeout = 15000
                connection.connect()

                if (connection.responseCode == HttpURLConnection.HTTP_OK) {
                    val tempDir = context.filesDir.resolve("images")
                    if (!tempDir.exists()) tempDir.mkdirs()
                    val tempFile = File(tempDir, "wallpaper_${System.currentTimeMillis()}.png")
                    connection.inputStream.use { input ->
                        tempFile.outputStream().use { output ->
                            input.copyTo(output)
                        }
                    }
                    tempFile
                } else {
                    Logging.log("SetWallpaperTool", "Failed to download image from $imageUrl, response code: ${connection.responseCode}")
                    null
                }
            }.getOrNull()
        }

        else -> {
            Logging.log("SetWallpaperTool", "Unsupported image URL scheme: $imageUrl")
            null
        }
    }
}